# CoTURN TURN server configuration
listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0
external-ip=$EXTERNAL_IP
realm=holocollab.local
server-name=coturn
lt-cred-mech
user=$TURNSERVER_USERNAME:$TURNSERVER_PASSWORD
log-file=stdout
verbose
no-cli
no-tcp-relay
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
allowed-peer-ip=0.0.0.0-255.255.255.255
min-port=$TURNSERVER_MIN_PORT
max-port=$TURNSERVER_MAX_PORT